# Generated by Django 4.1.2 on 2022-10-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.BigIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
