# Generated by Django 4.1.2 on 2022-10-29 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions_created_on_transactions_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 20, 55, 9, 829577, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('shopping', 'shopping'), ('fuel', 'fuel'), ('house_hold', 'house_hold')], max_length=50),
        ),
    ]
